version: '3.8'

services:
  reverse-proxy:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: secure_frontend
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: secure_backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:${MONGO_ROOT_PASSWORD}@mongo:27017/secureapp?authSource=admin
    secrets:
      - mongo_root_password
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:6.0
    container_name: secure_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_root_password
    volumes:
      - mongo_data:/data/db
    secrets:
      - mongo_root_password
    networks:
      - app_network

secrets:
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
